spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL:jdbc:sqlite:./data/moneyquest.db}
    driver-class-name: ${DATABASE_DRIVER:org.sqlite.JDBC}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.community.dialect.SQLiteDialect}
